// 错误码是 API 契约的一部分。
//
// 前端、测试、文档都可能依赖这些字符串。
// 如果它们散落在各个 service / middleware 里，后面拼错或改名会很难发现。
export const ERROR_CODE = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  USER_EMAIL_EXISTS: "USER_EMAIL_EXISTS",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TODO_NOT_FOUND: "TODO_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

// 这里得到的是一个字符串字面量联合类型：
//
// "AUTH_REQUIRED" | "INVALID_TOKEN" | ...
//
// 后面如果 AppError 的 code 使用 ErrorCode，
// TypeScript 就能帮我们发现拼写错误。
export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
